services:
  client:
    build: ../logger
    ports:
      - "4000:8080"
    environment:
      - NAME=client
  server:
    build: ../logger
    ports:
      - "4001:8080"
    environment:
      - NAME=server