version: '3'

services:
  client:
    build: ../logger
    environment:
      - NAME=client
  server:
    build: ../logger
    environment:
      - NAME=server
  reverse-proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf